In [2]:
#Consider the below code to answer further questions:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5']
array_list = np.array(object = list_)

In [3]:
list_

['1', '2', '3', '4', '5']

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.
# A1. 

 - Yes, there is a difference in the data type of the variables `list_` and `array_list`. The variable `list_` is a Python list, and `array_list` is a NumPy array. The data type of the elements in the NumPy array would be inferred based on the elements of the Python list.

I can print the data types of both variables using the following code:






In [10]:
print("Data type of list_:", type(list_[0]))
print("Data type of array_list:", array_list.dtype)

Data type of list_: <class 'str'>
Data type of array_list: <U1


# Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.
# A2. Following codes are to print data type of each and every element

In [11]:
# type of list_ elements
for i in list_:
    print(f'Data type of element in list_ {i} :', type(i))

Data type of element in list_ 1 : <class 'str'>
Data type of element in list_ 2 : <class 'str'>
Data type of element in list_ 3 : <class 'str'>
Data type of element in list_ 4 : <class 'str'>
Data type of element in list_ 5 : <class 'str'>


In [12]:
# type of array_list elements
for i in array_list:
    print(f' Data type of element in array_list {i} :', type(i))

 Data type of element in array_list 1 : <class 'numpy.str_'>
 Data type of element in array_list 2 : <class 'numpy.str_'>
 Data type of element in array_list 3 : <class 'numpy.str_'>
 Data type of element in array_list 4 : <class 'numpy.str_'>
 Data type of element in array_list 5 : <class 'numpy.str_'>


# Q3. Considering the following changes in the variable, 
# array_list: array_list = np.array(object = list_, dtype = int) 
# Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list?
# If so then print the data types of each and every element present in both the variables, list_ and arra_list.
# A3. 


In [14]:
# changes as per question
array_list = np.array(object = list_, dtype = int)
array_list

array([1, 2, 3, 4, 5])

**Yes , now the difference b/w data types of list_ and array_list as list_ datatype is still string but array_list elements are converted into numpy interger** 

In [16]:
# type of list_ elements
for i in list_:
    print(f'Data type of element in list_ {i} :', type(i))

Data type of element in list_ 1 : <class 'str'>
Data type of element in list_ 2 : <class 'str'>
Data type of element in list_ 3 : <class 'str'>
Data type of element in list_ 4 : <class 'str'>
Data type of element in list_ 5 : <class 'str'>


In [15]:
# type of array_list elements
for i in array_list:
    print(f' Data type of element in array_list {i} :', type(i))

 Data type of element in array_list 1 : <class 'numpy.int64'>
 Data type of element in array_list 2 : <class 'numpy.int64'>
 Data type of element in array_list 3 : <class 'numpy.int64'>
 Data type of element in array_list 4 : <class 'numpy.int64'>
 Data type of element in array_list 5 : <class 'numpy.int64'>


# Consider the below code to answer further questions:

In [18]:

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [19]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [20]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

# Q4. Write a code to find the following characteristics of variable, num_array:
 - (i) shape
 - (ii) size
 
 ##  A4. following are code to find the shape and size of num_array

In [25]:
# to find the size
np.size(num_array)

6

In [24]:
# to find the shape
np.shape(num_array)

(2, 3)

# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

# A5.

In [29]:
# using zeros numpy array creation function

arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
# shape and size of above array
print(f'shape of the array is , {arr.shape}')
print(f'size of the array is , {arr.size}')

shape of the array is , (3, 3)
size of the array is , 9


# Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
# A6.

In [ ]:
arr1 = np.eye(5)
arr1